In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("Titanic-Dataset.csv")

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [10]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (891, 12)
Columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [11]:
print("\nDataset Information:")
df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [14]:
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [15]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Fare"] = df["Fare"].fillna(df["Fare"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

print("\nMissing Values After Handling:")
print(df.isnull().sum())

Missing Values After Handling:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [17]:
print("Duplicate Records:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape After Removing Duplicates:", df.shape)

Duplicate Records: 0
Shape After Removing Duplicates: (891, 12)

In [18]:
le_sex = LabelEncoder()
le_embarked = LabelEncoder()

df["Sex"] = le_sex.fit_transform(df["Sex"])
df["Embarked"] = le_embarked.fit_transform(df["Embarked"])

print("Dataset After Encoding:")
print(df[["Sex", "Embarked"]].head())

Dataset After Encoding:
   Sex  Embarked
0    1         2
1    0         0
2    0         2
3    0         2
4    1         2

In [19]:
X = df[["Pclass", "Sex", "Age", "SibSp",
        "Parch", "Fare", "Embarked"]]
y = df["Survived"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (891, 7)
Target Shape: (891,)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 712
Testing Samples: 179

In [21]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled Training Features:")
print(X_train_scaled[:5])

print("\nScaled Testing Features:")
print(X_test_scaled[:5])

Scaled Training Features:
[[ 0.82956755  0.74242727 -0.00674143 -0.46508428 -0.46618317  0.5138115
   0.58489231]
 [-0.37094484  0.74242727 -0.00674143 -0.46508428 -0.46618317 -0.66256323
   0.58489231]
 [-1.57145722  0.74242727 -0.00674143 -0.46508428 -0.46618317  3.95539858
   0.58489231]
 [ 0.82956755 -1.34693328 -0.90625969 -0.46508428  0.72778236 -0.46787435
   0.58489231]
 [-0.37094484 -1.34693328  0.09328043  0.47833454  0.72778236 -0.11597681
   0.58489231]]

Scaled Testing Features:
[[ 0.82956755  0.74242727 -0.44493348  1.42175336 -0.46618317 -0.15970373
   0.58489231]
 [ 0.82956755  0.74242727  1.09282054 -0.46508428  0.72778236 -0.32732356
   0.58489231]
 [ 0.82956755  0.74242727 -0.59870888 -0.46508428 -0.46618317 -0.51212182
  -1.91626879]
 [ 0.82956755  0.74242727  0.86215744  1.42175336 -0.46618317 -0.36879541
   0.58489231]
 [ 0.82956755 -1.34693328 -0.00674143  0.47833454 -0.46618317 -0.33981696
  -0.66568824]]